### ISSUE TITLE
pageaccueilnode

### ISSUE THREAD

**Issue by karawitan** [Mayska/pageaccueilnode#1]
@Mayska ola !
 comment on fait pour utiliser cette page d'accueil ?

J'ai reussi a faire un npm install, ca m'a téléchargé 51 modules;

kalou@d64:~/pageaccueilnode$ find node_modules -maxdepth 1 -type d  | sed 's#node_modules/##' | tr '\n' ' '
node_modules cookie safe-buffer content-disposition path-to-regexp mime-types raw-body express parseurl encodeurl mime-db debug iconv-lite array-flatten send ipaddr.js toidentifier negotiator qs media-typer cookie-signature forwarded setprototypeof ee-first vary bytes destroy methods unpipe range-parser .bin ms inherits serve-static merge-descriptors utils-merge fresh accepts safer-buffer finalhandler escape-html type-is depd http-errors content-type proxy-addr etag statuses body-parser on-finished mime 

kalou@d64:~/pageaccueilnode$ find node_modules -maxdepth 1 -type d  | sed 's#node_modules/##' | tr '\n' ' '  | wc -w
51

Par contre ensuite .. "npm start" n'a rien lance .. qu'est-ce que j'ai fait de mal ?

**Comment by Mayska** [comment]
Salut,
Il te faut faire node app.js.

**Comment by karawitan** [comment]
merci, ca fonctionne beaucoup mieux en effet :)
